name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Main Application Docker Image
    - name: Build and Push Main Application Docker Image
      run: |
        docker build -t pradeepchoudhary31/small-app-project:latest .
        docker push pradeepchoudhary31/small-app-project:latest

    # Build and Push API Docker Image
    - name: Build and Push API Docker Image
      run: |
        docker build -t pradeepchoudhary31/small-app-project:latest .
        docker push pradeepchoudhary31/small-app-project:latest
